Document: visitfile
Title: Debian visitfile Manual
Author: <insert document author here>
Abstract: This manual describes what visitfile is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/visitfile/visitfile.sgml.gz

Format: postscript
Files: /usr/share/doc/visitfile/visitfile.ps.gz

Format: text
Files: /usr/share/doc/visitfile/visitfile.text.gz

Format: HTML
Index: /usr/share/doc/visitfile/html/index.html
Files: /usr/share/doc/visitfile/html/*.html
